
name: modpack-build-latest

on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted

    container:
      image: kalka/wolfpackmaker:latest
    steps:
      - name: "Checkout local repository"
        uses: actions/checkout@v2
      - name: "Clone wolfpackmaker"
        run: git clone https://github.com/kalkafox/wolfpackmaker.git
      - name: "Assemble lockfile"
        run: python3 wolfpackmaker/util/lock.py
      - name: "Get repo name"
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        shell: bash
      - name: "Package modpack contents"
        run: zip -r ${{ env.REPOSITORY_NAME }}.zip wolfpackmaker/wolfpackmaker.py wolfpackmaker/wolfpackmaker.bat wolfpackmaker/requirements.txt wolfpackmaker/multimc.bat .minecraft instance.cfg mmc-pack.json *.png
      - name: "Package config"
        run: zip -r config.zip .minecraft mmc-pack.json
      - name: Publish release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: |
            manifest.*
            *.zip
